//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Data {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Customer_Data.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer added successfully! ähnelt.
        /// </summary>
        internal static string AddCustomerSuccessful {
            get {
                return ResourceManager.GetString("AddCustomerSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Database ähnelt.
        /// </summary>
        internal static string Btn_CreateDatabaseText {
            get {
                return ResourceManager.GetString("Btn_CreateDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        internal static string Btn_QuitText {
            get {
                return ResourceManager.GetString("Btn_QuitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Database ähnelt.
        /// </summary>
        internal static string BtnOpenChoosenDatabase {
            get {
                return ResourceManager.GetString("BtnOpenChoosenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pay in ähnelt.
        /// </summary>
        internal static string BtnPayIn {
            get {
                return ResourceManager.GetString("BtnPayIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pay out ähnelt.
        /// </summary>
        internal static string BtnPayOut {
            get {
                return ResourceManager.GetString("BtnPayOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Database ähnelt.
        /// </summary>
        internal static string BtnSearchDatabase {
            get {
                return ResourceManager.GetString("BtnSearchDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FirstName ähnelt.
        /// </summary>
        internal static string DataGridFirstName {
            get {
                return ResourceManager.GetString("DataGridFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail address ähnelt.
        /// </summary>
        internal static string DataGridView_Column_EmailText {
            get {
                return ResourceManager.GetString("DataGridView_Column_EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First name ähnelt.
        /// </summary>
        internal static string DataGridView_Column_FirstNameText {
            get {
                return ResourceManager.GetString("DataGridView_Column_FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last change ähnelt.
        /// </summary>
        internal static string DataGridView_Column_LastChangeText {
            get {
                return ResourceManager.GetString("DataGridView_Column_LastChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last name ähnelt.
        /// </summary>
        internal static string DataGridView_Column_LastNameText {
            get {
                return ResourceManager.GetString("DataGridView_Column_LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credit ähnelt.
        /// </summary>
        internal static string DataGridView_Column_OpenBalanceText {
            get {
                return ResourceManager.GetString("DataGridView_Column_OpenBalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database created successfully! ähnelt.
        /// </summary>
        internal static string DBCreatedSuccesfully {
            get {
                return ResourceManager.GetString("DBCreatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No customer was added! ähnelt.
        /// </summary>
        internal static string FailureAddCustomer {
            get {
                return ResourceManager.GetString("FailureAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer could not be added! ähnelt.
        /// </summary>
        internal static string FailureAddCustomer_2 {
            get {
                return ResourceManager.GetString("FailureAddCustomer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database could not be created! ähnelt.
        /// </summary>
        internal static string FailureCreatingDatabase {
            get {
                return ResourceManager.GetString("FailureCreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect E-mail address! ähnelt.
        /// </summary>
        internal static string FailureInputTxbEmail {
            get {
                return ResourceManager.GetString("FailureInputTxbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfield can not be empty! ähnelt.
        /// </summary>
        internal static string FailureInputTxbNames_Empty {
            get {
                return ResourceManager.GetString("FailureInputTxbNames_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First letter must be a capital letter! ähnelt.
        /// </summary>
        internal static string FailureInputTxbNames_InvalidFirstLetter {
            get {
                return ResourceManager.GetString("FailureInputTxbNames_InvalidFirstLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database could not be opened! Check password! ähnelt.
        /// </summary>
        internal static string FailureOpenDatabase {
            get {
                return ResourceManager.GetString("FailureOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error loading the selected database! ähnelt.
        /// </summary>
        internal static string FailureOpenDatabaseMessageBox {
            get {
                return ResourceManager.GetString("FailureOpenDatabaseMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid characters are included! ähnelt.
        /// </summary>
        internal static string FailureTxbAmount {
            get {
                return ResourceManager.GetString("FailureTxbAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer To Database ähnelt.
        /// </summary>
        internal static string FormAddCustomer {
            get {
                return ResourceManager.GetString("FormAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AddDatabase ähnelt.
        /// </summary>
        internal static string FormAddDatabase {
            get {
                return ResourceManager.GetString("FormAddDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer Database Managment ähnelt.
        /// </summary>
        internal static string FormCustomerDatabase {
            get {
                return ResourceManager.GetString("FormCustomerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Existing Database ähnelt.
        /// </summary>
        internal static string FormOpenDatabase {
            get {
                return ResourceManager.GetString("FormOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payments ähnelt.
        /// </summary>
        internal static string FormPayments {
            get {
                return ResourceManager.GetString("FormPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database: ähnelt.
        /// </summary>
        internal static string Lbl_Database {
            get {
                return ResourceManager.GetString("Lbl_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No database selected. ähnelt.
        /// </summary>
        internal static string Lbl_DatabaseName_Default {
            get {
                return ResourceManager.GetString("Lbl_DatabaseName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the new database ähnelt.
        /// </summary>
        internal static string Lbl_NameNewDatabaseText {
            get {
                return ResourceManager.GetString("Lbl_NameNewDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string Lbl_PasswordText {
            get {
                return ResourceManager.GetString("Lbl_PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        internal static string LblAmount {
            get {
                return ResourceManager.GetString("LblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choosen Database ähnelt.
        /// </summary>
        internal static string LblChoosenDatabase {
            get {
                return ResourceManager.GetString("LblChoosenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail address ähnelt.
        /// </summary>
        internal static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        internal static string LblFirstName {
            get {
                return ResourceManager.GetString("LblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        internal static string LblLastName {
            get {
                return ResourceManager.GetString("LblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Money in the Account ähnelt.
        /// </summary>
        internal static string LblMoney {
            get {
                return ResourceManager.GetString("LblMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In order to be able to add a customer, a database must first be selected! ähnelt.
        /// </summary>
        internal static string NoDatabaseSelected {
            get {
                return ResourceManager.GetString("NoDatabaseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string ToolStripeMenüDatabase {
            get {
                return ResourceManager.GetString("ToolStripeMenüDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string ToolStripLanguage {
            get {
                return ResourceManager.GetString("ToolStripLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemaAddCustomer {
            get {
                return ResourceManager.GetString("ToolStripMenuItemaAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Database ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemaAddDatabase {
            get {
                return ResourceManager.GetString("ToolStripMenuItemaAddDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Database ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemaOpenDatabase {
            get {
                return ResourceManager.GetString("ToolStripMenuItemaOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Customer List ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemHideCustomerList {
            get {
                return ResourceManager.GetString("ToolStripMenuItemHideCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payments ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemPayments {
            get {
                return ResourceManager.GetString("ToolStripMenuItemPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Customer List ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemShowCustomerList {
            get {
                return ResourceManager.GetString("ToolStripMenuItemShowCustomerList", resourceCulture);
            }
        }
    }
}
