//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Data {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Customer_Data.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Database ähnelt.
        /// </summary>
        internal static string Btn_CreateDatabaseText {
            get {
                return ResourceManager.GetString("Btn_CreateDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        internal static string Btn_QuitText {
            get {
                return ResourceManager.GetString("Btn_QuitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Database ähnelt.
        /// </summary>
        internal static string BtnOpenChoosenDatabase {
            get {
                return ResourceManager.GetString("BtnOpenChoosenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Database ähnelt.
        /// </summary>
        internal static string BtnSearchDatabase {
            get {
                return ResourceManager.GetString("BtnSearchDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FirstName ähnelt.
        /// </summary>
        internal static string DataGridFirstName {
            get {
                return ResourceManager.GetString("DataGridFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer To Database ähnelt.
        /// </summary>
        internal static string FormAddCustomer {
            get {
                return ResourceManager.GetString("FormAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AddDatabase ähnelt.
        /// </summary>
        internal static string FormAddDatabase {
            get {
                return ResourceManager.GetString("FormAddDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer Database Managment ähnelt.
        /// </summary>
        internal static string FormCustomerDatabase {
            get {
                return ResourceManager.GetString("FormCustomerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Existing Database ähnelt.
        /// </summary>
        internal static string FormOpenDatabase {
            get {
                return ResourceManager.GetString("FormOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the new database ähnelt.
        /// </summary>
        internal static string Lbl_NameNewDatabaseText {
            get {
                return ResourceManager.GetString("Lbl_NameNewDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string Lbl_PasswordText {
            get {
                return ResourceManager.GetString("Lbl_PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choosen Database ähnelt.
        /// </summary>
        internal static string LblChoosenDatabase {
            get {
                return ResourceManager.GetString("LblChoosenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail address ähnelt.
        /// </summary>
        internal static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        internal static string LblFirstName {
            get {
                return ResourceManager.GetString("LblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        internal static string LblLastName {
            get {
                return ResourceManager.GetString("LblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Money in the Account ähnelt.
        /// </summary>
        internal static string LblMoney {
            get {
                return ResourceManager.GetString("LblMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string ToolStripeMenüDatabase {
            get {
                return ResourceManager.GetString("ToolStripeMenüDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string ToolStripLanguage {
            get {
                return ResourceManager.GetString("ToolStripLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemaAddCustomer {
            get {
                return ResourceManager.GetString("ToolStripMenuItemaAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Database ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemaAddDatabase {
            get {
                return ResourceManager.GetString("ToolStripMenuItemaAddDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Database ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemaOpenDatabase {
            get {
                return ResourceManager.GetString("ToolStripMenuItemaOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Customer List ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemHideCustomerList {
            get {
                return ResourceManager.GetString("ToolStripMenuItemHideCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payments ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemPayments {
            get {
                return ResourceManager.GetString("ToolStripMenuItemPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Customer List ähnelt.
        /// </summary>
        internal static string ToolStripMenuItemShowCustomerList {
            get {
                return ResourceManager.GetString("ToolStripMenuItemShowCustomerList", resourceCulture);
            }
        }
    }
}
